# Publishes NPM package to Github Packages

name: Publish NPM package

on:
  release:
    types: [created]

jobs:
  publish:
    uses: vector-remote-care/github-actions/.github/workflows/npm-publish.yml@master
    with:
      node_version: '14'
      is_build_required: false
    secrets:
      GPR_READ_TOKEN: ${{ secrets.GPR_READ_TOKEN }}